<?php include_once('Fo/header.php'); ?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="css/default.css" />
    <link rel="icon" type="image/x-icon" href="fonts/favicon.ico" />

</head>
<body>
<section>
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
            <div class="card-image">
          <img src="img/d.jpg">
        <span class="card-title">¿Que desea hacer?</span>
        </div>
                
        <div class="row">
                                <div class="col s6 m4">
                                <div class="card">
                                    <div class="card-image">
                                    <img src="img/ventas.png" width="230" height="150">
                                    <span class="card-title">Productos en Stock</span>
                                    </div>
                                    <div class="card-content">
                                    <p>I am a very simple card. I am good at containing small bits of information.
                                    I am convenient because I require little markup to use effectively.</p>
                                    </div>
                                    <div class="card-action">
                                    <a href="Charts/Productos/productos.php">Productos</a>
                                    </div>
                                </div>
                                </div>

                                <div class="col s6 m4">
                                <div class="card">
                                    <div class="card-image">
                                    <img src="img/cliente.jpg" width="230" height="150">
                                    <span class="card-title">Clientes</span>
                                    </div>
                                    <div class="card-content">
                                    <p>I am a very simple card. I am good at containing small bits of information.
                                    I am convenient because I require little markup to use effectively.</p>
                                    </div>
                                    <div class="card-action">
                                    <a href="graficos/ejemplo2.html">Graficar</a>
                                    </div>
                                </div>
                                </div>

                                <div class="col s6 m4">
                                <div class="card">
                                    <div class="card-image" >
                                    <img src="img/dinero.jpg" width="230" height="150">
                                    <span class="card-title">Ganancias</span>
                                    </div>
                                    <div class="card-content">
                                    <p>I am a very simple card. I am good at containing small bits of information.
                                    I am convenient because I require little markup to use effectively.</p>
                                    </div>
                                    <div class="card-action">
                                    <a href="../graficos/ejemplo2.html">Graficar</a>
                                    </div>
                                </div>
                                </div>
                                <div class="col s6 m4">
                                <div class="card">
                                    <div class="card-image" >
                                    <img src="img/dinero.jpg" width="230" height="150">
                                    <span class="card-title">Ganancias</span>
                                    </div>
                                    <div class="card-content">
                                    <p>I am a very simple card. I am good at containing small bits of information.
                                    I am convenient because I require little markup to use effectively.</p>
                                    </div>
                                    <div class="card-action">
                                    <a href="Charts/VentasComp/ejemplo.php">Graficar</a>
                                    </div>
                                </div>
                                </div>

                               </div>
                 </div>
             </div>
        </div>
    </div>
    <!-------------------------------------------------------------------------------- Ventana Modal---------------------------------------------------------------------------->

<!--------------------------------------------------------------------------------- FIN VENTANA MODAL---------------------------------------------------------------------->


    <script type="text/javascript" src="js/jquery-3.0.0.min.js"></script>
    <script type="text/javascript" src="js/materialize.min.js"></script>
    <script type="text/javascript" src="js/jquery.validate.min.js"></script>
    </section>
    <?php include('Fo/footer.php');?>
